AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'config/spring.rb'

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'