userspec:
  hpcguest4:
    python_path: 'singularity exec --nv /home/hpc/hpcguest4/sifs/keras-230704.sif python3'
    active_learning_keras_base: "/home/hpc/hpcguest4/ActiveLoopProject/pkl-keras-train"
  kaidong:
    python_path: 'singularity exec --nv /home/kaidong/ubuntu/keras-new.sif python3'
    active_learning_keras_base: "/home/kaidong/PycharmProjects/pkl-keras-train"

with_agentformer: true
#working_directory: "/home/kaidong/PycharmProjects/pkl-keras-train"
sample_amount:
  train: 1000
  valid: 0
