userspec:
  hpcguest4:
    singularity_container: '/home/hpc/hpcguest4/sifs/pkl-keras-train.sif'
    active_learning_keras_base: '/home/hpc/hpcguest4/ActiveLoopProject/pkl-keras-train'
    python_path: 'singularity exec --nv /home/hpc/hpcguest4/sifs/keras-230704.sif python3'
  kaidong:
    singularity_container: '/home/kaidong/Projects/PythonProjects/pkl-keras-train/sifs/keras.sif'
    active_learning_keras_base: '/home/kaidong/Projects/PythonProjects/pkl-keras-train'
    python_path: 'singularity exec --nv ./sifs/keras.sif python3'

with_agentformer: true
#working_directory: "/home/kaidong/PycharmProjects/pkl-keras-train"
sample_amount:
  train: 500
  valid: 0
