userspec:
  hpcguest4:
    steersuite_exec_base: "/home/hpc/hpcguest4/ActiveLoopProject/SteerSuite-P2/build/bin"
    steersuite_exec_cmd: "singularity exec --env LD_LIBRARY_PATH=$LD_LIBRARY_PATH --nv /home/hpc/hpcguest4/sifs/hlsix-220922.sif ./steersim -commandline"
  kaidong:
    steersuite_exec_base: "/home/kaidong/SteerSuite-P2/build/bin"
    steersuite_exec_cmd: "./steersim -commandline"

steersuite_record_pool: "steersimRecord-generated"
steersuite_process_pool: "steersimRecord-generated-process"
steersuite_config_path: "config/extern/steersim-config.xml"

scene_defs:
  - scene1
  - scene2
  - scene3
  - scene4
  - scene5
  - scene6
  - scene7
  - scene8
  - scene9
  - scene10
  - scene_evac_orca
  - scene_evac_orca_1
  - scene_evac_orca_2
  - scene_evac_orca_3
  - scene_evac_orca_4
  - scene_evac_orca_5
  - scene_evac_orca_6
  - scene_evac_sf

steersuite_scene:
  basic:
    scene1:
      parameter_size: 9
      nagent: 2
    scene2:
      parameter_size: 21
      nagent: 2
    scene3:
      parameter_size: 15
      nagent: 2
    scene4:
      parameter_size: 19
      nagent: 3
    scene5:
      parameter_size: 11
      nagent: 2
    scene6:
      parameter_size: 15
      nagent: 4
    scene7:
      parameter_size: 19
      nagent: 6
    scene8:
      parameter_size: 13
      nagent: 3
    scene9:
      parameter_size: 15
      nagent: 4
    scene10:
      parameter_size: 17
      nagent: 5

    scene_evac_orca:
      scene_name: sceneEvacORCA
      parameter_size: 376
      nagent: 75
      env_parameter_size: 1
      agent_parameter_size: 5
    scene_evac_orca_1:
      scene_name: sceneEvacOrca1
      parameter_size: 1
      nagent: 75
      env_parameter_size: 1
      agent_parameter_size: 0
    scene_evac_orca_2:
      scene_name: sceneEvacOrca2
      parameter_size: 75
      nagent: 75
      env_parameter_size: 0
      agent_parameter_size: 1
    scene_evac_orca_3:
      scene_name: sceneEvacOrca3
      parameter_size: 75
      nagent: 75
      env_parameter_size: 0
      agent_parameter_size: 1
    scene_evac_orca_4:
      scene_name: sceneEvacOrca4
      parameter_size: 75
      nagent: 75
      env_parameter_size: 0
      agent_parameter_size: 1
    scene_evac_orca_5:
      scene_name: sceneEvacOrca5
      parameter_size: 75
      nagent: 75
      env_parameter_size: 0
      agent_parameter_size: 1
    scene_evac_orca_6:
      scene_name: sceneEvacOrca6
      parameter_size: 75
      nagent: 75
      env_parameter_size: 0
      agent_parameter_size: 1

    scene_evac_sf:
      scene_name: sceneEvacSF
      parameter_size: 976
      nagent: 75
      ai: social-force
      env_parameter_size: 1
      agent_parameter_size: 13

