% if ENV['USER'] =~ /hpcguest/
steersuite_exec_base: "/home/hpc/hpcguest4/ActiveLoopProject/SteerSuite-P2/build/bin"
steersuite_exec_cmd: "singularity exec --env LD_LIBRARY_PATH=$LD_LIBRARY_PATH --nv /home/hpc/hpcguest4/sifs/hlsix-220922.sif ./steersim -commandline -config minimal2.xml"
% else
steersuite_exec_base: "/home/kaidong/SteerSuite-P2/build/bin"
steersuite_exec_cmd: "./steersim -commandline -config minimal2.xml"
%end
steersuite_record_pool: "steersimRecord-new-train"
steersuite_process_pool: "steersimRecord-new-train-process"
