userspec:
  hpcguest4:
    steersuite_exec_base: "/home/hpc/hpcguest4/ActiveLoopProject/SteerSuite-P2/build/bin"
    steersuite_exec_cmd: "singularity exec --env LD_LIBRARY_PATH=$LD_LIBRARY_PATH --nv /home/hpc/hpcguest4/sifs/hlsix-220922.sif ./steersim -commandline -config minimal2.xml"
  kaidong:
    steersuite_exec_base: "/home/kaidong/SteerSuite-P2/build/bin"
    steersuite_exec_cmd: "./steersim -commandline"

steersuite_record_pool: "steersimRecord-generated"
steersuite_process_pool: "steersimRecord-generated-process"
steersuite_config_path: "config/extern/steersim-config.xml"

scene_defs:
  - scene1
  - scene2
  - scene3
  - scene4
  - scene5
  - scene6

steersuite_scene:
  basic:
    scene1:
      parameter_size: 9
      nagent: 2
    scene2:
      parameter_size: 21
      nagent: 2
    scene3:
      parameter_size: 15
      nagent: 2
    scene4:
      parameter_size: 19
      nagent: 3
    scene5:
      parameter_size: 11
      nagent: 2
    scene6:
      parameter_size: 15
      nagent: 4

