userspec:
  hpcguest4:
    steersuite_exec_base: "/home/hpc/hpcguest4/ActiveLoopProject/SteerSuite-P2/build/bin"
    steersuite_exec_cmd: "singularity exec --env LD_LIBRARY_PATH=$LD_LIBRARY_PATH --nv /home/hpc/hpcguest4/sifs/steersim-240718.sif ./steersim -commandline"
  kaidong:
    steersuite_exec_base: "/home/kaidong/Projects/SteerProjects/MySteerSuite/build/bin"
    steersuite_exec_cmd: "singularity exec --env LD_LIBRARY_PATH=$LD_LIBRARY_PATH /home/kaidong/Projects/SteerProjects/steersim.sif ./steersim -commandline"

steersuite_record_pool: "steersimRecord-generated"
steersuite_process_pool: "steersimRecord-generated-process"
steersuite_config_path: "config/extern/steersim-config.xml"

scene_defs:
  - scene1
  - scene2
  - scene3
  - scene4
  - scene5
  - scene6
  - scene7
  - scene8
  - scene9
  - scene10
  - scene_evac_orca
  - scene_evac_orca_1
  - scene_evac_orca_2
  - scene_evac_orca_3
  - scene_evac_orca_4
  - scene_evac_orca_5
  - scene_evac_orca_6
  - scene_evac_sf
  - scene_evac_sf_0
  - scene_evac_sf_1
  - scene_evac_sf_2
  - scene_evac_sf_3
  - scene_evac_sf_4
  - scene_evac_sf_5
  - scene_evac_sf_6
  - scene_evac_sf_7
  - scene_evac_sf_8
  - scene_evac_sf_9
  - scene_evac_sf_10
  - scene_evac_sf_11
  - scene_evac_sf_12
  - scene_evac_sf_13
  - scene_evac_sf_14
  - scene_evac_cog
  - scene_evac_cog_1
  - scene_evac_cog_2
  - scene_evac_cog_3
  - scene_evac_cog_4
  - scene_evac_cog_5
  - scene_evac_cog_6
  - scene_evac_cog_7
  - scene_evac_cog_8
  - scene_evac_cog_9
  - scene_evac_cog_10
  - scene_evac_cog_11

steersuite_scene:
  basic:
    scene1:
      parameter_size: 9
      nagent: 2
    scene2:
      parameter_size: 21
      nagent: 2
    scene3:
      parameter_size: 15
      nagent: 2
    scene4:
      parameter_size: 19
      nagent: 3
    scene5:
      parameter_size: 11
      nagent: 2
    scene6:
      parameter_size: 15
      nagent: 4
    scene7:
      parameter_size: 19
      nagent: 6
    scene8:
      parameter_size: 13
      nagent: 3
    scene9:
      parameter_size: 15
      nagent: 4
    scene10:
      parameter_size: 17
      nagent: 5

    _evac_single_parameter: &evac_single_parameter
      parameter_size: 75
      nagent: 75
      env_parameter_size: 0
      agent_parameter_size: 1

    scene_evac_orca:
      scene_name: sceneEvacORCA
      parameter_size: 376
      nagent: 75
      env_parameter_size: 1
      agent_parameter_size: 5
    scene_evac_orca_1:
      <<: *evac_single_parameter
      scene_name: sceneEvacOrca1
    scene_evac_orca_2:
      scene_name: sceneEvacOrca2
      <<: *evac_single_parameter
    scene_evac_orca_3:
      scene_name: sceneEvacOrca3
      <<: *evac_single_parameter
    scene_evac_orca_4:
      scene_name: sceneEvacOrca4
      <<: *evac_single_parameter
    scene_evac_orca_5:
      scene_name: sceneEvacOrca5
      <<: *evac_single_parameter
    scene_evac_orca_6:
      scene_name: sceneEvacOrca6
      <<: *evac_single_parameter

    scene_evac_sf:
      scene_name: sceneEvacSF
      parameter_size: 976
      nagent: 75
      ai: social-force
      env_parameter_size: 1
      agent_parameter_size: 13
    scene_evac_sf_1:
      scene_name: sceneEvacSF1
      <<: *evac_single_parameter
      ai: social-force
    scene_evac_sf_2:
      scene_name: sceneEvacSF2
      <<: *evac_single_parameter
      ai: social-force
    scene_evac_sf_3:
      scene_name: sceneEvacSF3
      <<: *evac_single_parameter
      ai: social-force
    scene_evac_sf_4:
      scene_name: sceneEvacSF4
      <<: *evac_single_parameter
      ai: social-force
    scene_evac_sf_5:
      scene_name: sceneEvacSF5
      <<: *evac_single_parameter
      ai: social-force
    scene_evac_sf_6:
      scene_name: sceneEvacSF6
      <<: *evac_single_parameter
      ai: social-force
    scene_evac_sf_7:
      scene_name: sceneEvacSF7
      <<: *evac_single_parameter
      ai: social-force
    scene_evac_sf_8:
      scene_name: sceneEvacSF8
      <<: *evac_single_parameter
      ai: social-force
    scene_evac_sf_9:
      scene_name: sceneEvacSF9
      <<: *evac_single_parameter
      ai: social-force
    scene_evac_sf_10:
      scene_name: sceneEvacSF10
      <<: *evac_single_parameter
      ai: social-force
    scene_evac_sf_11:
      scene_name: sceneEvacSF11
      <<: *evac_single_parameter
      ai: social-force
    scene_evac_sf_12:
      scene_name: sceneEvacSF12
      <<: *evac_single_parameter
      ai: social-force
    scene_evac_sf_13:
      scene_name: sceneEvacSF13
      <<: *evac_single_parameter
      ai: social-force
    scene_evac_sf_14:
      scene_name: sceneEvacSF14
      <<: *evac_single_parameter
      ai: social-force

    scene_evac_cog:
      scene_name: sceneEvacCOG
      parameter_size: 751
      nagent: 75
      ai: egocentric-cognitive
      env_parameter_size: 1
      agent_parameter_size: 10
    scene_evac_cog_1:
      scene_name: sceneEvacCOG1
      <<: *evac_single_parameter
      ai: egocentric-cognitive
    scene_evac_cog_2:
      scene_name: sceneEvacCOG2
      <<: *evac_single_parameter
      ai: egocentric-cognitive
    scene_evac_cog_3:
      scene_name: sceneEvacCOG3
      <<: *evac_single_parameter
      ai: egocentric-cognitive
    scene_evac_cog_4:
      scene_name: sceneEvacCOG4
      <<: *evac_single_parameter
      ai: egocentric-cognitive
    scene_evac_cog_5:
      scene_name: sceneEvacCOG5
      <<: *evac_single_parameter
      ai: egocentric-cognitive
    scene_evac_cog_6:
      scene_name: sceneEvacCOG6
      <<: *evac_single_parameter
      ai: egocentric-cognitive
    scene_evac_cog_7:
      scene_name: sceneEvacCOG7
      <<: *evac_single_parameter
      ai: egocentric-cognitive
    scene_evac_cog_8:
      scene_name: sceneEvacCOG8
      <<: *evac_single_parameter
      ai: egocentric-cognitive
    scene_evac_cog_9:
      scene_name: sceneEvacCOG9
      <<: *evac_single_parameter
      ai: egocentric-cognitive
    scene_evac_cog_10:
      scene_name: sceneEvacCOG10
      <<: *evac_single_parameter
      ai: egocentric-cognitive
    scene_evac_cog_11:
      scene_name: sceneEvacCOG11
      <<: *evac_single_parameter
      ai: egocentric-cognitive
